### ISSUE TITLE
Não consigo acessar o nome do usuário.

### ISSUE THREAD

**Issue by ishiikurisu** [ishiikurisu/S2BProj#1]
Quando enviamos um usuário à página principal, não consigo acessar o nome dele; o sistema acusa uma `NullReferenceException`. Alguma ideia do porquê que isso acontece?

**Comment by ygordanniel** [comment]
É porque quando tu passa pra página principal usa como construtor só o email e a senha. O nome ainda não foi setado. O nome vai ser setado depois de pesquisar no banco.

**Comment by ygordanniel** [comment]
Na hora de construir a página vai ter que fazer uma pesquisa no banco retornando todas as informações do usuário pra poder construir a página com o nome e tal.

**Comment by ishiikurisu** [comment]
Ok, vou tentar arrumar isso agora então. Acabei de diferenciar (bem zoado) adicionar evento de mover o mapa. :')

**Comment by JorgeAndd** [comment]
Eu to fazendo a função de pegar o usuario do banco.
Rapidão que eu já termino e dou commit

**Comment by ishiikurisu** [comment]
Ok, vou deixar por conta então

**Comment by ygordanniel** [comment]
Na hora de tu construir a página, só deixa comentado pra mim onde que tem que atribuir as informações do Usuário que eu arrumo o Controller pra fazer isso.

**Comment by JorgeAndd** [comment]
Pronto, só usar DatabaseConnection.GetUsuario(email).
A função retorna um objeto Usuario.
Esse objeto tem as informações que pegou do banco, exceto a senha por questão de segurança.

Vou dar commit

**Comment by JorgeAndd** [comment]
Comentei umas partes do PageSearch.xaml.cs, tava dando erro na hora de compilar

**Comment by ishiikurisu** [comment]
É na hora de entrar com o Usuário na MainPage. O objeto já era transferido com nome nulo.

**Comment by ishiikurisu** [comment]
Essa versão atual travou o PC do SENAI kkkk estou tentando desfragmentar o computador agora para ver se não é alguma corrupção louca aqui

**Comment by ishiikurisu** [comment]
Era alguma viagem do computador mesmo. Está funcionando. O usuário já deve aparecer com nome na hora do objeto `Usuario` ser criado, lá no arquivo PaginaEntrar

**Comment by ygordanniel** [comment]
Ok, vou arrumar isso.

**Comment by ishiikurisu** [comment]
arrumado :dancer:
